ALTER TABLE SZRAPLY ADD acceptedTerms NVARCHAR(1);
ALTER TABLE SZRAPLY ADD acceptedTermsTimestamp DATETIME2;
ALTER TABLE SZRAPLY ADD ipAddressAtAccountCreation NVARCHAR(40);
ALTER TABLE SZRAPLY ADD ipAddressAtAppCreation NVARCHAR(40);
ALTER TABLE SZRAPLY ADD phoneType NVARCHAR(10);
ALTER TABLE SZRAPLY ADD mailingAddressValidationOverride NVARCHAR(1);
ALTER TABLE SZRAPLY ADD fraudScore NUMERIC(18,5);
ALTER TABLE SZRAPLY ADD fraudStatus INT;