-- Placement View table.
create table SZRPLMT (plmtSequence INT,
                    pidm INT,
                    cccId NVARCHAR(12),
                    ssid NVARCHAR(20),
                    misCode NVARCHAR(3),
                    dataSource SMALLINT,
                    english INT,
                    slam INT,
                    stem INT,
                    isAlgI NVARCHAR(16),
                    isAlgII NVARCHAR(16),
                    trigonometry NVARCHAR(16),
                    preCalculus NVARCHAR(16),
                    calculus NVARCHAR(16),
                    completedEleventhGrade NVARCHAR(16),
                    cumulativeGradePointAverage NUMERIC(3,2),
                    englishCompletedCourseId SMALLINT,
                    englishCompletedCourseGrade NVARCHAR(32),
                    mathematicsCompletedCourseId SMALLINT,
                    mathematicsCompletedCourseGrade NVARCHAR(32),
                    mathematicsPassedCourseId SMALLINT,
                    mathematicsPassedCourseGrade NVARCHAR(32),
                    placementStatus NVARCHAR(80),
                    tstmpERPTransmit DATETIME2,
                    tstmpSISTransmit DATETIME2,
                    sisProcessedFlag NVARCHAR(4),
                    tstmpSISProcessed DATETIME2,
                    sisProcessedNotes NVARCHAR(1024),
                    appId BIGINT,
                    highestGradeCompleted NVARCHAR(2)
);

create sequence placementSequence as INT START WITH 1 INCREMENT BY 1;
