ALTER TABLE SZRPGRT ADD acceptedTerms NVARCHAR(1);
ALTER TABLE SZRPGRT ADD acceptedTermsTimestamp DATETIME2;
ALTER TABLE SZRPGRT ADD ipAddressAtAccountCreation NVARCHAR(40);
ALTER TABLE SZRPGRT ADD ipAddressAtAppCreation NVARCHAR(40);
ALTER TABLE SZRPGRT ADD phoneType NVARCHAR(10);
ALTER TABLE SZRPGRT ADD mailingAddressValidationOverride NVARCHAR(1);
ALTER TABLE SZRPGRT ADD studentParent NVARCHAR(1);