ACCEPT owner CHAR PROMPT 'Adaptor user: ';
ALTER TABLE "&owner".SZRINTL ADD (  ACCEPTED_TERMS VARCHAR2(1 CHAR) );
ALTER TABLE "&owner".SZRINTL ADD (  ACCEPTED_TERMS_TSTMP DATE );
ALTER TABLE "&owner".SZRINTL ADD (  IP_ADDR_ACCT_CREATE VARCHAR2(40 CHAR) );
ALTER TABLE "&owner".SZRINTL ADD (  IP_ADDR_APP_CREATE VARCHAR2(40 CHAR) );
ALTER TABLE "&owner".SZRINTL ADD (  PHONE_TYPE VARCHAR2(10 CHAR) );
/