ACCEPT owner CHAR PROMPT 'Adaptor user: ';
ALTER TABLE "&owner".SZRINTL ADD (  PREF_CONTACT_METHOD VARCHAR2(255 CHAR) );
ALTER TABLE "&owner".SZRINTL ADD (  ADDRESS_VAL_OVERRIDE VARCHAR2(1 CHAR) );
ALTER TABLE "&owner".SZRINTL ADD (  ADDRESS_VAL_OVER_TSTMP DATE );
ALTER TABLE "&owner".SZRINTL ADD (  EMAIL_VERIFIED VARCHAR2(1 CHAR) );
ALTER TABLE "&owner".SZRINTL ADD (  EMAIL_VERIFIED_TSTMP DATE );
ALTER TABLE "&owner".SZRINTL ADD (  PHONE_VERIFIED VARCHAR2(1 CHAR) );
ALTER TABLE "&owner".SZRINTL ADD (  PHONE_VERIFIED_TSTMP DATE );
/
/