ACCEPT owner CHAR PROMPT 'Adaptor user: ';
ALTER TABLE "&owner".SZRINTL ADD (  IDME_CONFIRMATION_TSTMP TIMESTAMP (6) );
ALTER TABLE "&owner".SZRINTL ADD (  IDME_OPTIN_TSTMP TIMESTAMP(6) );
ALTER TABLE "&owner".SZRINTL ADD (  IDME_WORKFLOW_STATUS VARCHAR2(50 CHAR) );
/