ACCEPT owner CHAR PROMPT 'Adaptor user: ';
ACCEPT tablespace CHAR DEFAULT 'USERS' PROMPT 'Tablespace owner: ';
CREATE SEQUENCE "&owner".SZRFRAD_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE "&owner".SZRFRAD (
         SZRFRAD_REPORT_ID NUMBER,
         SZRFRAD_MIS_CODE VARCHAR2(4 CHAR),
         SZRFRAD_APP_ID NUMBER,
         SZRFRAD_CCCID VARCHAR2(12 CHAR),
         SZRFRAD_TYPE VARCHAR2(20 CHAR),
         SZRFRAD_REPORTING_MIS VARCHAR2(4 CHAR),
         SZRFRAD_TSTMP_SUBMIT TIMESTAMP,
         SZRFRAD_SIS_PROC_FLAG VARCHAR2(1 CHAR),
         SZRFRAD_SIS_TSTMP_PROC TIMESTAMP,
         SZRFRAD_SIS_PROC_NOTE VARCHAR2(100 CHAR),
         SZRFRAD_REPORT_SOURCE VARCHAR2(30 CHAR)
) TABLESPACE &tablespace
/
CREATE OR REPLACE PUBLIC SYNONYM SZRFRAD_SEQ FOR "&owner".SZRFRAD_SEQ;
/
CREATE OR REPLACE PUBLIC SYNONYM SZRFRAD FOR "&owner".SZRFRAD;
/
