alter table SZRPLMT modify SZRPLMT_CCCID VARCHAR2(320 CHAR);
alter table SZRPLMT modify SZRPLMT_STATEWIDE_STUDENT_ID VARCHAR2(160 CHAR);
alter table SZRPLMT modify SZRPLMT_MIS_CODE VARCHAR2(320 CHAR);
alter table SZRPLMT modify SZRPLMT_IS_ALG_I VARCHAR2(16 CHAR);
alter table SZRPLMT modify SZRPLMT_IS_ALG_II VARCHAR2(16 CHAR);
alter table SZRPLMT modify SZRPLMT_TRIGONOMETRY VARCHAR2(16 CHAR);
alter table SZRPLMT modify SZRPLMT_PRE_CALCULUS VARCHAR2(16 CHAR);
alter table SZRPLMT modify SZRPLMT_CALCULUS VARCHAR2(16 CHAR);
alter table SZRPLMT modify SZRPLMT_COMPLETED_11TH_GRADE VARCHAR2(16 CHAR);
alter table SZRPLMT modify SZRPLMT_ENG_COMP_COURSE_GRADE VARCHAR2(32 CHAR);
alter table SZRPLMT modify SZRPLMT_MATH_COMP_COURSE_GRADE VARCHAR2(32 CHAR);
alter table SZRPLMT modify SZRPLMT_MATH_PASS_COURSE_GRADE VARCHAR2(32 CHAR);
alter table SZRPLMT modify SZRPLMT_USER_ID VARCHAR2(480 CHAR);
alter table SZRPLMT modify SZRPLMT_VPDI_CODE VARCHAR2(96 CHAR);
alter table SZRPLMT modify SZRPLMT_STATUS VARCHAR2(80 CHAR);
alter table SZRPLMT modify SZRPLMT_SIS_PROCESSED_FLAG VARCHAR2(4 CHAR);
alter table SZRPLMT modify SZRPLMT_SIS_PROCESSED_NOTES VARCHAR2(1024 CHAR);
/