ACCEPT owner CHAR PROMPT 'Adaptor user: ';
ALTER TABLE "&owner".SZRPGRT ADD (  ELIG_EXONERATED_CRIME VARCHAR2(1 CHAR) );
ALTER TABLE "&owner".SZRPGRT ADD (  ELIG_COVID_DEATH VARCHAR2(1 CHAR) );
COMMENT ON COLUMN "&owner"."SZRPGRT"."ELIG_EXONERATED_CRIME" IS 'eligExoneratedCrime';
COMMENT ON COLUMN "&owner"."SZRPGRT"."ELIG_COVID_DEATH" IS 'eligCovidDeath';