ACCEPT owner CHAR PROMPT 'Adaptor user: ';
ALTER TABLE "&owner".SZRPGRT ADD (  ACCEPTED_TERMS VARCHAR2(1 CHAR) );
ALTER TABLE "&owner".SZRPGRT ADD (  ACCEPTED_TERMS_TSTMP DATE );
ALTER TABLE "&owner".SZRPGRT ADD (  IP_ADDR_ACCT_CREATE VARCHAR2(40 CHAR) );
ALTER TABLE "&owner".SZRPGRT ADD (  IP_ADDR_APP_CREATE VARCHAR2(40 CHAR) );
ALTER TABLE "&owner".SZRPGRT ADD (  PHONE_TYPE VARCHAR2(10 CHAR) );
ALTER TABLE "&owner".SZRPGRT ADD (  MAIL_ADDR_VALIDATION_OVR VARCHAR2(1 CHAR) );
ALTER TABLE "&owner".SZRPGRT ADD (  STUDENT_PARENT VARCHAR2(1 CHAR) );
/