ACCEPT owner CHAR PROMPT 'Adaptor user: ';
ALTER TABLE "&owner".SZRSAPP ADD (  ACCEPTED_TERMS VARCHAR2(1 CHAR) );
ALTER TABLE "&owner".SZRSAPP ADD (  ACCEPTED_TERMS_TSTMP DATE );
ALTER TABLE "&owner".SZRSAPP ADD (  IP_ADDR_ACCT_CREATE VARCHAR2(40 CHAR) );
ALTER TABLE "&owner".SZRSAPP ADD (  IP_ADDR_APP_CREATE VARCHAR2(40 CHAR) );
ALTER TABLE "&owner".SZRSAPP ADD (  PHONE_TYPE VARCHAR2(10 CHAR) );
ALTER TABLE "&owner".SZRSAPP ADD (  MAIL_ADDR_VALIDATION_OVR VARCHAR2(1 CHAR) );
ALTER TABLE "&owner".SZRSAPP ADD (  FRAUD_SCORE NUMBER );
ALTER TABLE "&owner".SZRSAPP ADD (  FRAUD_STATUS NUMBER );
ALTER TABLE "&owner".SZRSAPP ADD (  STUDENT_PARENT VARCHAR2(1 CHAR) );
/