package api.banner

import com.ccctc.adaptor.exception.EntityConflictException
import com.ccctc.adaptor.exception.EntityNotFoundException
import com.ccctc.adaptor.exception.InternalServerException
import com.ccctc.adaptor.model.apply.Application
import com.ccctc.adaptor.model.apply.SupplementalQuestions
import com.ccctc.adaptor.util.MisEnvironment
import groovy.sql.GroovyRowResult
import groovy.sql.Sql
import groovy.util.logging.Slf4j
import org.springframework.core.env.Environment

import java.sql.Timestamp
import java.sql.Date
import java.time.format.DateTimeFormatter

@Slf4j
class Apply {

    Environment environment

    static Map<String, MetaProperty> appProperties = Application.metaClass.properties.collectEntries { [(it.name.toUpperCase()): it] }
    static Map<String, MetaProperty> supProperties = SupplementalQuestions.metaClass.properties.collectEntries { [(it.name.toUpperCase()): it] }

    def get(String misCode, Long id) {
        Sql sql = BannerConnection.getSession(environment, misCode)

        try {
            def applicationQuery = MisEnvironment.getProperty(environment, misCode, "sqljdbc.application.applicationQuery")
            GroovyRowResult applicationRec = sql.firstRow(applicationQuery, [appId: id])

            if (!applicationRec)
                throw new EntityNotFoundException()


            def returnApplication = new Application()
            mapValues(appProperties, applicationRec, returnApplication)

            returnApplication.supplementalQuestions = new SupplementalQuestions()
            mapValues(supProperties, applicationRec, returnApplication.supplementalQuestions)

            return returnApplication
        } finally {
            sql.close()
        }
    }

    def post(String misCode, Application application) {
        Sql sql = BannerConnection.getSession(environment, misCode)

        try {
            def applicationQuery = MisEnvironment.getProperty(environment, misCode, "sqljdbc.application.applicationQuery")

            def applicationrec = sql.firstRow(applicationQuery, [appId: application.getAppId()])
            if (applicationrec)
                throw new EntityConflictException("Application ID already exists")

            createApply(misCode, application, sql)
        } finally {
            sql.close()
        }

        try {
            return get(misCode, application.appId)
        } catch (EntityNotFoundException e) {
            throw new InternalServerException("POST reported success, but GET failed to find record")
        }
    }

    def createApply(String misCode, application, Sql sql) {
       def insertQuery = MisEnvironment.getProperty(environment, misCode, "sqljdbc.application.insertQuery")
        try {
            sql.execute(insertQuery, ["preferredMethodOfContact": application.preferredMethodOfContact,
                                   "mainphoneVerified": Utility.convertBoolToYesNo(application.mainphoneVerified),
                                   "mainphoneVerifiedTimestamp": application.mainphoneVerifiedTimestamp != null ? Timestamp.valueOf(application.mainphoneVerifiedTimestamp): null,
                                   "emailVerified": Utility.convertBoolToYesNo(application.emailVerified),
                                   "emailVerifiedTimestamp": application.emailVerifiedTimestamp != null ? Timestamp.valueOf(application.emailVerifiedTimestamp): null,
                                   "addressValidationOverride": Utility.convertBoolToYesNo(application.addressValidationOverride),
                                   "addressValidationOverrideTimestamp": application.addressValidationOverrideTimestamp != null ? Timestamp.valueOf(application.addressValidationOverrideTimestamp): null,
                                   "mailingAddressValidationOverride": Utility.convertBoolToYesNo(application.mailingAddressValidationOverride),
                                   "acceptedTerms": Utility.convertBoolToYesNo(application.acceptedTerms),
                                   "acceptedTermsTimestamp": application.acceptedTermsTimestamp != null ? Timestamp.valueOf(application.acceptedTermsTimestamp): null,
                                   "appId": application.appId,
                                   "cccId": application.cccId,
                                   "status": application.status,
                                   "fraudScore": application.fraudScore,
                                   "fraudStatus": application.fraudStatus,
                                   "collegeId": application.collegeId,
                                   "termId": application.termId,
                                   "majorId": application.majorId,
                                   "intendedMajor": application.intendedMajor,
                                   "eduGoal": application.eduGoal,
                                   "highestEduLevel": application.highestEduLevel,
                                   "consentIndicator": Utility.convertBoolToYesNo(application.consentIndicator),
                                   "appLang": application.appLang,
                                   "ackFinAid": Utility.convertBoolToYesNo(application.ackFinAid),
                                   "finAidRef": Utility.convertBoolToYesNo(application.finAidRef),
                                   "confirmation": application.confirmation,
                                   "supPageCode": application.supPageCode,
                                   "lastPage": application.lastPage,
                                   "streetaddress1": application.streetaddress1,
                                   "streetaddress2": application.streetaddress2,
                                   "city": application.city,
                                   "postalcode": application.postalcode,
                                   "state": application.state,
                                   "nonusaprovince": application.nonusaprovince,
                                   "country": application.country,
                                   "nonUsAddress": Utility.convertBoolToYesNo(application.nonUsAddress),
                                   "email": application.email,
                                   "permStreetaddress1": application.permStreetaddress1,
                                   "permStreetaddress2": application.permStreetaddress2,
                                   "permCity": application.permCity,
                                   "permPostalcode": application.permPostalcode,
                                   "permState": application.permState,
                                   "permNonusaprovince": application.permNonusaprovince,
                                   "permCountry": application.permCountry,
                                   "addressSame": Utility.convertBoolToYesNo(application.addressSame),
                                   "mainphone": application.mainphone,
                                   "mainphoneExt": application.mainphoneExt,
                                   "mainphoneAuthText": Utility.convertBoolToYesNo(application.mainphoneAuthText),
                                   "secondphone": application.secondphone,
                                   "secondphoneExt": application.secondphoneExt,
                                   "secondphoneAuthText": Utility.convertBoolToYesNo(application.secondphoneAuthText),
                                   "phoneType": application.phoneType,
                                   "enrollStatus": application.enrollStatus,
                                   "hsEduLevel": application.hsEduLevel,
                                   "hsCompDate": application.hsCompDate != null ? Date.valueOf(application.hsCompDate): null,
                                   "higherEduLevel": application.higherEduLevel,
                                   "higherCompDate": application.higherCompDate != null ? Date.valueOf(application.higherCompDate): null,
                                   "hsNotAttended": Utility.convertBoolToYesNo(application.hsNotAttended),
                                   "cahsGraduated": Utility.convertBoolToYesNo(application.cahsGraduated),
                                   "cahs3year": Utility.convertBoolToYesNo(application.cahs3year),
                                   "hsName": application.hsName,
                                   "hsCity": application.hsCity,
                                   "hsState": application.hsState,
                                   "hsCountry": application.hsCountry,
                                   "hsCds": application.hsCds,
                                   "hsCeeb": application.hsCeeb,
                                   "hsNotListed": Utility.convertBoolToYesNo(application.hsNotListed),
                                   "homeSchooled": Utility.convertBoolToYesNo(application.homeSchooled),
                                   "collegeCount": application.collegeCount,
                                   "hsAttendance": application.hsAttendance,
                                   "coenrollConfirm": Utility.convertBoolToYesNo(application.coenrollConfirm),
                                   "gender": application.gender,
                                   "pgFirstname": application.pgFirstname,
                                   "pgLastname": application.pgLastname,
                                   "pgRel": application.pgRel,
                                   "pg1Edu": application.pg1Edu,
                                   "pg2Edu": application.pg2Edu,
                                   "pgEduMis": application.pgEduMis,
                                   "under19Ind": Utility.convertBoolToYesNo(application.under19Ind),
                                   "dependentStatus": application.dependentStatus,
                                   "raceEthnic": application.raceEthnic,
                                   "hispanic": Utility.convertBoolToYesNo(application.hispanic),
                                   "raceGroup": application.raceGroup,
                                   "raceEthnicFull": application.raceEthnicFull,
                                   "ssn": application.ssn,
                                   "birthdate": application.birthdate != null ? Date.valueOf(application.birthdate): null,
                                   "firstname": application.firstname,
                                   "middlename": application.middlename,
                                   "lastname": application.lastname,
                                   "suffix": application.suffix,
                                   "otherfirstname": application.otherfirstname,
                                   "othermiddlename": application.othermiddlename,
                                   "otherlastname": application.otherlastname,
                                   "citizenshipStatus": application.citizenshipStatus,
                                   "alienRegNumber": application.alienRegNumber,
                                   "studentParent": Utility.convertBoolToYesNo(application.studentParent),
                                   "visaType": application.visaType,
                                   "noDocuments": Utility.convertBoolToYesNo(application.noDocuments),
                                   "alienRegIssueDate": application.alienRegIssueDate != null ? Date.valueOf(application.alienRegIssueDate): null,
                                   "alienRegExpireDate": application.alienRegExpireDate != null ? Date.valueOf(application.alienRegExpireDate): null,
                                   "alienRegNoExpire": Utility.convertBoolToYesNo(application.alienRegNoExpire),
                                   "militaryStatus": application.militaryStatus,
                                   "militaryDischargeDate": application.militaryDischargeDate != null ? Date.valueOf(application.militaryDischargeDate): null,
                                   "militaryHomeState": application.militaryHomeState,
                                   "militaryHomeCountry": application.militaryHomeCountry,
                                   "militaryCaStationed": Utility.convertBoolToYesNo(application.militaryCaStationed),
                                   "militaryLegalResidence": application.militaryLegalResidence,
                                   "caRes2Years": Utility.convertBoolToYesNo(application.caRes2Years),
                                   "caDateCurrent": application.caDateCurrent != null ? Date.valueOf(application.caDateCurrent): null,
                                   "caNotArrived": Utility.convertBoolToYesNo(application.caNotArrived),
                                   "caCollegeEmployee": Utility.convertBoolToYesNo(application.caCollegeEmployee),
                                   "caSchoolEmployee": Utility.convertBoolToYesNo(application.caSchoolEmployee),
                                   "caSeasonalAg": Utility.convertBoolToYesNo(application.caSeasonalAg),
                                   "caFosterYouth": Utility.convertBoolToYesNo(application.caFosterYouth),
                                   "caOutsideTax": Utility.convertBoolToYesNo(application.caOutsideTax),
                                   "caOutsideTaxYear": application.caOutsideTaxYear != null ? Date.valueOf(application.caOutsideTaxYear): null,
                                   "caOutsideVoted": Utility.convertBoolToYesNo(application.caOutsideVoted),
                                   "caOutsideVotedYear": application.caOutsideVotedYear != null ? Date.valueOf(application.caOutsideVotedYear): null,
                                   "caOutsideCollege": Utility.convertBoolToYesNo(application.caOutsideCollege),
                                   "caOutsideCollegeYear": application.caOutsideCollegeYear != null ? Date.valueOf(application.caOutsideCollegeYear): null,
                                   "caOutsideLawsuit": Utility.convertBoolToYesNo(application.caOutsideLawsuit),
                                   "caOutsideLawsuitYear": application.caOutsideLawsuitYear != null ? Date.valueOf(application.caOutsideLawsuitYear): null,
                                   "resStatus": application.resStatus,
                                   "resStatusChange": Utility.convertBoolToYesNo(application.resStatusChange),
                                   "resPrevDate": application.resPrevDate != null ? Date.valueOf(application.resPrevDate): null,
                                   "admIneligible": application.admIneligible,
                                   "eligAb540": Utility.convertBoolToYesNo(application.eligAb540),
                                   "resAreaA": application.resAreaA,
                                   "resAreaB": application.resAreaB,
                                   "resAreaC": application.resAreaC,
                                   "resAreaD": application.resAreaD,
                                   "experience": application.experience,
                                   "recommend": application.recommend,
                                   "comments": application.comments,
                                   "comfortableEnglish": Utility.convertBoolToYesNo(application.comfortableEnglish),
                                   "financialAssistance": Utility.convertBoolToYesNo(application.financialAssistance),
                                   "tanfSsiGa": Utility.convertBoolToYesNo(application.tanfSsiGa),
                                   "fosterYouths": Utility.convertBoolToYesNo(application.fosterYouths),
                                   "athleticIntercollegiate": Utility.convertBoolToYesNo(application.athleticIntercollegiate),
                                   "athleticIntramural": Utility.convertBoolToYesNo(application.athleticIntramural),
                                   "athleticNotInterested": Utility.convertBoolToYesNo(application.athleticNotInterested),
                                   "academicCounseling": Utility.convertBoolToYesNo(application.academicCounseling),
                                   "basicSkills": Utility.convertBoolToYesNo(application.basicSkills),
                                   "calworks": Utility.convertBoolToYesNo(application.calworks),
                                   "careerPlanning": Utility.convertBoolToYesNo(application.careerPlanning),
                                   "childCare": Utility.convertBoolToYesNo(application.childCare),
                                   "counselingPersonal": Utility.convertBoolToYesNo(application.counselingPersonal),
                                   "dsps": Utility.convertBoolToYesNo(application.dsps),
                                   "eops": Utility.convertBoolToYesNo(application.eops),
                                   "esl": Utility.convertBoolToYesNo(application.esl),
                                   "healthServices": Utility.convertBoolToYesNo(application.healthServices),
                                   "housingInfo": Utility.convertBoolToYesNo(application.housingInfo),
                                   "employmentAssistance": Utility.convertBoolToYesNo(application.employmentAssistance),
                                   "onlineClasses": Utility.convertBoolToYesNo(application.onlineClasses),
                                   "reentryProgram": Utility.convertBoolToYesNo(application.reentryProgram),
                                   "scholarshipInfo": Utility.convertBoolToYesNo(application.scholarshipInfo),
                                   "studentGovernment": Utility.convertBoolToYesNo(application.studentGovernment),
                                   "testingAssessment": Utility.convertBoolToYesNo(application.testingAssessment),
                                   "transferInfo": Utility.convertBoolToYesNo(application.transferInfo),
                                   "tutoringServices": Utility.convertBoolToYesNo(application.tutoringServices),
                                   "veteransServices": Utility.convertBoolToYesNo(application.veteransServices),
                                   "integrityFg01": Utility.convertBoolToYesNo(application.integrityFg01),
                                   "integrityFg02": Utility.convertBoolToYesNo(application.integrityFg02),
                                   "integrityFg03": Utility.convertBoolToYesNo(application.integrityFg03),
                                   "integrityFg04": Utility.convertBoolToYesNo(application.integrityFg04),
                                   "integrityFg11": Utility.convertBoolToYesNo(application.integrityFg11),
                                   "integrityFg47": Utility.convertBoolToYesNo(application.integrityFg47),
                                   "integrityFg48": Utility.convertBoolToYesNo(application.integrityFg48),
                                   "integrityFg49": Utility.convertBoolToYesNo(application.integrityFg49),
                                   "integrityFg50": Utility.convertBoolToYesNo(application.integrityFg50),
                                   "integrityFg51": Utility.convertBoolToYesNo(application.integrityFg51),
                                   "integrityFg52": Utility.convertBoolToYesNo(application.integrityFg52),
                                   "integrityFg53": Utility.convertBoolToYesNo(application.integrityFg53),
                                   "integrityFg54": Utility.convertBoolToYesNo(application.integrityFg54),
                                   "integrityFg55": Utility.convertBoolToYesNo(application.integrityFg55),
                                   "integrityFg56": Utility.convertBoolToYesNo(application.integrityFg56),
                                   "integrityFg57": Utility.convertBoolToYesNo(application.integrityFg57),
                                   "integrityFg58": Utility.convertBoolToYesNo(application.integrityFg58),
                                   "integrityFg59": Utility.convertBoolToYesNo(application.integrityFg59),
                                   "integrityFg60": Utility.convertBoolToYesNo(application.integrityFg60),
                                   "integrityFg61": Utility.convertBoolToYesNo(application.integrityFg61),
                                   "integrityFg62": Utility.convertBoolToYesNo(application.integrityFg62),
                                   "integrityFg63": Utility.convertBoolToYesNo(application.integrityFg63),
                                   "integrityFg70": Utility.convertBoolToYesNo(application.integrityFg70),
                                   "integrityFg80": Utility.convertBoolToYesNo(application.integrityFg80),
                                   "col1Ceeb": application.col1Ceeb,
                                   "col1Cds": application.col1Cds,
                                   "col1NotListed": Utility.convertBoolToYesNo(application.col1NotListed),
                                   "col1Name": application.col1Name,
                                   "col1City": application.col1City,
                                   "col1State": application.col1State,
                                   "col1Country": application.col1Country,
                                   "col1StartDate": application.col1StartDate != null ? Date.valueOf(application.col1StartDate): null,
                                   "col1EndDate": application.col1EndDate != null ? Date.valueOf(application.col1EndDate): null,
                                   "col1DegreeDate": application.col1DegreeDate != null ? Date.valueOf(application.col1DegreeDate): null,
                                   "col1DegreeObtained": application.col1DegreeObtained,
                                   "col2Ceeb": application.col2Ceeb,
                                   "col2Cds": application.col2Cds,
                                   "col2NotListed": Utility.convertBoolToYesNo(application.col2NotListed),
                                   "col2Name": application.col2Name,
                                   "col2City": application.col2City,
                                   "col2State": application.col2State,
                                   "col2Country": application.col2Country,
                                   "col2StartDate": application.col2StartDate != null ? Date.valueOf(application.col2StartDate): null,
                                   "col2EndDate": application.col2EndDate != null ? Date.valueOf(application.col2EndDate): null,
                                   "col2DegreeDate": application.col2DegreeDate != null ? Date.valueOf(application.col2DegreeDate): null,
                                   "col2DegreeObtained": application.col2DegreeObtained,
                                   "col3Ceeb": application.col3Ceeb,
                                   "col3Cds": application.col3Cds,
                                   "col3NotListed": Utility.convertBoolToYesNo(application.col3NotListed),
                                   "col3Name": application.col3Name,
                                   "col3City": application.col3City,
                                   "col3State": application.col3State,
                                   "col3Country": application.col3Country,
                                   "col3StartDate": application.col3StartDate != null ? Date.valueOf(application.col3StartDate): null,
                                   "col3EndDate": application.col3EndDate != null ? Date.valueOf(application.col3EndDate): null,
                                   "col3DegreeDate": application.col3DegreeDate != null ? Date.valueOf(application.col3DegreeDate): null,
                                   "col3DegreeObtained": application.col3DegreeObtained,
                                   "col4Ceeb": application.col4Ceeb,
                                   "col4Cds": application.col4Cds,
                                   "col4NotListed": Utility.convertBoolToYesNo(application.col4NotListed),
                                   "col4Name": application.col4Name,
                                   "col4City": application.col4City,
                                   "col4State": application.col4State,
                                   "col4Country": application.col4Country,
                                   "col4StartDate": application.col4StartDate != null ? Date.valueOf(application.col4StartDate): null,
                                   "col4EndDate": application.col4EndDate != null ? Date.valueOf(application.col4EndDate): null,
                                   "col4DegreeDate": application.col4DegreeDate != null ? Date.valueOf(application.col4DegreeDate): null,
                                   "col4DegreeObtained": application.col4DegreeObtained,
                                   "collegeName": application.collegeName,
                                   "districtName": application.districtName,
                                   "termCode": application.termCode,
                                   "termDescription": application.termDescription,
                                   "majorCode": application.majorCode,
                                   "majorDescription": application.majorDescription,
                                   "tstmpSubmit": application.tstmpSubmit != null ? Timestamp.valueOf(application.tstmpSubmit): null,
                                   "tstmpCreate": application.tstmpCreate != null ? Timestamp.valueOf(application.tstmpCreate): null,
                                   "tstmpUpdate": application.tstmpUpdate != null ? Timestamp.valueOf(application.tstmpUpdate): null,
                                   "ssnDisplay": application.ssnDisplay,
                                   "fosterYouthStatus": application.fosterYouthStatus,
                                   "fosterYouthPreference": Utility.convertBoolToYesNo(application.fosterYouthPreference),
                                   "fosterYouthMis": Utility.convertBoolToYesNo(application.fosterYouthMis),
                                   "fosterYouthPriority": Utility.convertBoolToYesNo(application.fosterYouthPriority),
                                   "tstmpDownload": application.tstmpDownload != null ? Timestamp.valueOf(application.tstmpDownload): null,
                                   "addressValidation": application.addressValidation,
                                   "zip4": application.zip4,
                                   "permAddressValidation": application.permAddressValidation,
                                   "permZip4": application.permZip4,
                                   "dischargeType": application.dischargeType,
                                   "collegeExpelledSummary": Utility.convertBoolToYesNo(application.collegeExpelledSummary),
                                   "col1ExpelledStatus": Utility.convertBoolToYesNo(application.col1ExpelledStatus),
                                   "col2ExpelledStatus": Utility.convertBoolToYesNo(application.col2ExpelledStatus),
                                   "col3ExpelledStatus": Utility.convertBoolToYesNo(application.col3ExpelledStatus),
                                   "col4ExpelledStatus": Utility.convertBoolToYesNo(application.col4ExpelledStatus),
                                   "integrityFlags": application.integrityFlags,
                                   "rdd": application.rdd != null ? Date.valueOf(application.rdd): null,
                                   "ssnType": application.ssnType,
                                   "militaryStationedCaEd": Utility.convertBoolToYesNo(application.militaryStationedCaEd),
                                   "integrityFg65": Utility.convertBoolToYesNo(application.integrityFg65),
                                   "integrityFg64": Utility.convertBoolToYesNo(application.integrityFg64),
                                   "ipAddress": application.ipAddress,
                                   "campaign1": application.campaign1,
                                   "campaign2": application.campaign2,
                                   "campaign3": application.campaign3,
                                   "orientation": application.orientation,
                                   "transgender": application.transgender,
                                   "ssnException": Utility.convertBoolToYesNo(application.ssnException),
                                   "integrityFg71": Utility.convertBoolToYesNo(application.integrityFg71),
                                   "preferredFirstname": application.preferredFirstname,
                                   "preferredMiddlename": application.preferredMiddlename,
                                   "preferredLastname": application.preferredLastname,
                                   "preferredName": Utility.convertBoolToYesNo(application.preferredName),
                                   "ssnNo": Utility.convertBoolToYesNo(application.ssnNo),
                                   "completedEleventhGrade": Utility.convertBoolToYesNo(application.completedEleventhGrade),
                                   "gradePointAverage": application.gradePointAverage,
                                   "highestEnglishCourse": application.highestEnglishCourse,
                                   "highestEnglishGrade": application.highestEnglishGrade,
                                   "highestMathCourseTaken": application.highestMathCourseTaken,
                                   "highestMathTakenGrade": application.highestMathTakenGrade,
                                   "highestMathCoursePassed": application.highestMathCoursePassed,
                                   "highestMathPassedGrade": application.highestMathPassedGrade,
                                   "integrityFg30": Utility.convertBoolToYesNo(application.integrityFg30),
                                   "hsCdsFull": application.hsCdsFull,
                                   "col1CdsFull": application.col1CdsFull,
                                   "col2CdsFull": application.col2CdsFull,
                                   "col3CdsFull": application.col3CdsFull,
                                   "col4CdsFull": application.col4CdsFull,
                                   "ssid": application.ssid,
                                   "noPermAddressHomeless": Utility.convertBoolToYesNo(application.noPermAddressHomeless),
                                   "noMailingAddressHomeless": Utility.convertBoolToYesNo(application.noMailingAddressHomeless),
                                   "termStart": application.termStart != null ? Date.valueOf(application.termStart): null,
                                   "termEnd": application.termEnd != null ? Date.valueOf(application.termEnd): null,
                                   "homelessYouth": Utility.convertBoolToYesNo(application.homelessYouth),
                                   "integrityFg40": Utility.convertBoolToYesNo(application.integrityFg40),
                                   "cipCode": application.cipCode,
                                   "majorCategory": application.majorCategory,
                                   "mainphoneintl": application.mainphoneintl,
                                   "secondphoneintl": application.secondphoneintl,
                                   "suppText01": application.supplementalQuestions?.suppText01,
                                   "suppText02": application.supplementalQuestions?.suppText02,
                                   "suppText03": application.supplementalQuestions?.suppText03,
                                   "suppText04": application.supplementalQuestions?.suppText04,
                                   "suppText05": application.supplementalQuestions?.suppText05,
                                   "suppText06": application.supplementalQuestions?.suppText06,
                                   "suppText07": application.supplementalQuestions?.suppText07,
                                   "suppText08": application.supplementalQuestions?.suppText08,
                                   "suppText09": application.supplementalQuestions?.suppText09,
                                   "suppText10": application.supplementalQuestions?.suppText10,
                                   "suppText11": application.supplementalQuestions?.suppText11,
                                   "suppText12": application.supplementalQuestions?.suppText12,
                                   "suppText13": application.supplementalQuestions?.suppText13,
                                   "suppText14": application.supplementalQuestions?.suppText14,
                                   "suppText15": application.supplementalQuestions?.suppText15,
                                   "suppText16": application.supplementalQuestions?.suppText16,
                                   "suppText17": application.supplementalQuestions?.suppText17,
                                   "suppText18": application.supplementalQuestions?.suppText18,
                                   "suppText19": application.supplementalQuestions?.suppText19,
                                   "suppText20": application.supplementalQuestions?.suppText20,
                                   "suppCheck01": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck01),
                                   "suppCheck02": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck02),
                                   "suppCheck03": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck03),
                                   "suppCheck04": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck04),
                                   "suppCheck05": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck05),
                                   "suppCheck06": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck06),
                                   "suppCheck07": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck07),
                                   "suppCheck08": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck08),
                                   "suppCheck09": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck09),
                                   "suppCheck10": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck10),
                                   "suppCheck11": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck11),
                                   "suppCheck12": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck12),
                                   "suppCheck13": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck13),
                                   "suppCheck14": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck14),
                                   "suppCheck15": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck15),
                                   "suppCheck16": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck16),
                                   "suppCheck17": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck17),
                                   "suppCheck18": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck18),
                                   "suppCheck19": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck19),
                                   "suppCheck20": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck20),
                                   "suppCheck21": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck21),
                                   "suppCheck22": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck22),
                                   "suppCheck23": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck23),
                                   "suppCheck24": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck24),
                                   "suppCheck25": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck25),
                                   "suppCheck26": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck26),
                                   "suppCheck27": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck27),
                                   "suppCheck28": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck28),
                                   "suppCheck29": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck29),
                                   "suppCheck30": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck30),
                                   "suppCheck31": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck31),
                                   "suppCheck32": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck32),
                                   "suppCheck33": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck33),
                                   "suppCheck34": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck34),
                                   "suppCheck35": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck35),
                                   "suppCheck36": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck36),
                                   "suppCheck37": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck37),
                                   "suppCheck38": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck38),
                                   "suppCheck39": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck39),
                                   "suppCheck40": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck40),
                                   "suppCheck41": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck41),
                                   "suppCheck42": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck42),
                                   "suppCheck43": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck43),
                                   "suppCheck44": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck44),
                                   "suppCheck45": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck45),
                                   "suppCheck46": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck46),
                                   "suppCheck47": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck47),
                                   "suppCheck48": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck48),
                                   "suppCheck49": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck49),
                                   "suppCheck50": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck50),
                                   "suppYesno01": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno01),
                                   "suppYesno02": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno02),
                                   "suppYesno03": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno03),
                                   "suppYesno04": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno04),
                                   "suppYesno05": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno05),
                                   "suppYesno06": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno06),
                                   "suppYesno07": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno07),
                                   "suppYesno08": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno08),
                                   "suppYesno09": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno09),
                                   "suppYesno10": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno10),
                                   "suppYesno11": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno11),
                                   "suppYesno12": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno12),
                                   "suppYesno13": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno13),
                                   "suppYesno14": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno14),
                                   "suppYesno15": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno15),
                                   "suppYesno16": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno16),
                                   "suppYesno17": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno17),
                                   "suppYesno18": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno18),
                                   "suppYesno19": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno19),
                                   "suppYesno20": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno20),
                                   "suppYesno21": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno21),
                                   "suppYesno22": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno22),
                                   "suppYesno23": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno23),
                                   "suppYesno24": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno24),
                                   "suppYesno25": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno25),
                                   "suppYesno26": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno26),
                                   "suppYesno27": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno27),
                                   "suppYesno28": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno28),
                                   "suppYesno29": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno29),
                                   "suppYesno30": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno30),
                                   "suppMenu01": application.supplementalQuestions?.suppMenu01,
                                   "suppMenu02": application.supplementalQuestions?.suppMenu02,
                                   "suppMenu03": application.supplementalQuestions?.suppMenu03,
                                   "suppMenu04": application.supplementalQuestions?.suppMenu04,
                                   "suppMenu05": application.supplementalQuestions?.suppMenu05,
                                   "suppMenu06": application.supplementalQuestions?.suppMenu06,
                                   "suppMenu07": application.supplementalQuestions?.suppMenu07,
                                   "suppMenu08": application.supplementalQuestions?.suppMenu08,
                                   "suppMenu09": application.supplementalQuestions?.suppMenu09,
                                   "suppMenu10": application.supplementalQuestions?.suppMenu10,
                                   "suppMenu11": application.supplementalQuestions?.suppMenu11,
                                   "suppMenu12": application.supplementalQuestions?.suppMenu12,
                                   "suppMenu13": application.supplementalQuestions?.suppMenu13,
                                   "suppMenu14": application.supplementalQuestions?.suppMenu14,
                                   "suppMenu15": application.supplementalQuestions?.suppMenu15,
                                   "suppMenu16": application.supplementalQuestions?.suppMenu16,
                                   "suppMenu17": application.supplementalQuestions?.suppMenu17,
                                   "suppMenu18": application.supplementalQuestions?.suppMenu18,
                                   "suppMenu19": application.supplementalQuestions?.suppMenu19,
                                   "suppMenu20": application.supplementalQuestions?.suppMenu20,
                                   "suppMenu21": application.supplementalQuestions?.suppMenu21,
                                   "suppMenu22": application.supplementalQuestions?.suppMenu22,
                                   "suppMenu23": application.supplementalQuestions?.suppMenu23,
                                   "suppMenu24": application.supplementalQuestions?.suppMenu24,
                                   "suppMenu25": application.supplementalQuestions?.suppMenu25,
                                   "suppMenu26": application.supplementalQuestions?.suppMenu26,
                                   "suppMenu27": application.supplementalQuestions?.suppMenu27,
                                   "suppMenu28": application.supplementalQuestions?.suppMenu28,
                                   "suppMenu29": application.supplementalQuestions?.suppMenu29,
                                   "suppMenu30": application.supplementalQuestions?.suppMenu30,
                                   "suppDate01": application.supplementalQuestions?.suppDate01 != null ? Date.valueOf(application.supplementalQuestions?.suppDate01): null,
                                   "suppDate02": application.supplementalQuestions?.suppDate02 != null ? Date.valueOf(application.supplementalQuestions?.suppDate02): null,
                                   "suppDate03": application.supplementalQuestions?.suppDate03 != null ? Date.valueOf(application.supplementalQuestions?.suppDate03): null,
                                   "suppDate04": application.supplementalQuestions?.suppDate04 != null ? Date.valueOf(application.supplementalQuestions?.suppDate04): null,
                                   "suppDate05": application.supplementalQuestions?.suppDate05 != null ? Date.valueOf(application.supplementalQuestions?.suppDate05): null,
                                   "suppState01": application.supplementalQuestions?.suppState01,
                                   "suppState02": application.supplementalQuestions?.suppState02,
                                   "suppState03": application.supplementalQuestions?.suppState03,
                                   "suppState04": application.supplementalQuestions?.suppState04,
                                   "suppState05": application.supplementalQuestions?.suppState05,
                                   "suppCountry01": application.supplementalQuestions?.suppCountry01,
                                   "suppCountry02": application.supplementalQuestions?.suppCountry02,
                                   "suppCountry03": application.supplementalQuestions?.suppCountry03,
                                   "suppCountry04": application.supplementalQuestions?.suppCountry04,
                                   "suppCountry05": application.supplementalQuestions?.suppCountry05,
                                   "suppPhonenumber01": application.supplementalQuestions?.suppPhonenumber01,
                                   "suppPhonenumber02": application.supplementalQuestions?.suppPhonenumber02,
                                   "suppPhonenumber03": application.supplementalQuestions?.suppPhonenumber03,
                                   "suppPhonenumber04": application.supplementalQuestions?.suppPhonenumber04,
                                   "suppPhonenumber05": application.supplementalQuestions?.suppPhonenumber05,
                                   "suppSecret01": application.supplementalQuestions?.suppSecret01,
                                   "suppSecret02": application.supplementalQuestions?.suppSecret02,
                                   "suppSecret03": application.supplementalQuestions?.suppSecret03,
                                   "suppSecret04": application.supplementalQuestions?.suppSecret04,
                                   "suppSecret05": application.supplementalQuestions?.suppSecret05,
                                   "integrityFg81": Utility.convertBoolToYesNo(application.integrityFg81),
                                   "nonCredit": Utility.convertBoolToYesNo(application.nonCredit),
                                   "highestGradeCompleted": application.highestGradeCompleted,
                                   "ipAddressAtAccountCreation": application.ipAddressAtAccountCreation,
                                   "ipAddressAtAppCreation": application.ipAddressAtAppCreation,
                                   "idmeConfirmationTimestamp": application.idmeConfirmationTimestamp != null ? Timestamp.valueOf(application.idmeConfirmationTimestamp): null,
                                   "idmeOptinTimestamp": application.idmeOptinTimestamp != null ? Timestamp.valueOf(application.idmeOptinTimestamp): null,
                                   "idmeWorkflowStatus": application.idmeWorkflowStatus,
                                   "raceAIANOtherDescription": application.raceAIANOtherDescription,
                                   "studentDepsUnder18": application.studentDepsUnder18,
                                   "studentDeps18Over": application.studentDeps18Over
                                   ])
        }

        catch (Exception e) {
          throw new InternalServerException("Server encountered an error: " + e.getMessage())
        }
    }

    static void mapValues(Map<String, MetaProperty> propertyMap, Map source, Object destination) {
        // map values from SQL Map to any Object
        if( source?.containsKey("mailingAddressValOverride"))
            source.put("mailingAddressValidationOverride", source.get("mailingAddressValOverride"))
        Utility.mapValues(propertyMap, source, destination)
    }

}