package api.banner

import com.ccctc.adaptor.exception.EntityConflictException
import com.ccctc.adaptor.exception.EntityNotFoundException
import com.ccctc.adaptor.exception.InternalServerException
import com.ccctc.adaptor.model.apply.InternationalApplication
import com.ccctc.adaptor.model.apply.SupplementalQuestions
import com.ccctc.adaptor.util.MisEnvironment
import groovy.sql.GroovyRowResult
import groovy.sql.Sql
import groovy.util.logging.Slf4j
import org.springframework.core.env.Environment

import java.sql.Date
import java.sql.Timestamp

@Slf4j
class InternationalApply {

    Environment environment

    static Map<String, MetaProperty> appProperties = InternationalApplication.metaClass.properties.collectEntries { [(it.name.toUpperCase()): it] }
    static Map<String, MetaProperty> supProperties = SupplementalQuestions.metaClass.properties.collectEntries { [(it.name.toUpperCase()): it] }

    def get(String misCode, Long id) {
        Sql sql = BannerConnection.getSession(environment, misCode)

        try {
            def applicationQuery = MisEnvironment.getProperty(environment, misCode, "sqljdbc.application.internationalApplicationQuery")

            def applicationRec = sql.firstRow(applicationQuery, [appId: id])

            if (!applicationRec)
                throw new EntityNotFoundException()

            def returnApplication = new InternationalApplication()
            mapValues(appProperties, applicationRec, returnApplication)

            returnApplication.supplementalQuestions = new SupplementalQuestions()
            mapValues(supProperties, applicationRec, returnApplication.supplementalQuestions)

            return returnApplication
        } finally {
            sql.close()
        }
    }

    def post(String misCode, InternationalApplication application) {
        Sql sql = BannerConnection.getSession(environment, misCode)

        try {
            def applicationQuery = MisEnvironment.getProperty(environment, misCode, "sqljdbc.application.internationalApplicationQuery")
            def applicationrec = sql.firstRow(applicationQuery, [appId: application.getAppId()])
            if (applicationrec)
                throw new EntityConflictException("InternationalApplication ID already exists")

            createInternationalApply(misCode, application, sql)
        } finally {
            sql.close()
        }

        try {
            return get(misCode, application.appId)
        } catch (EntityNotFoundException e) {
            throw new InternalServerException("POST reported success, but GET failed to find record")
        }
    }

    def createInternationalApply(String misCode, InternationalApplication application, Sql sql) {
        def insertQuery = MisEnvironment.getProperty(environment, misCode, "sqljdbc.application.internationalInsertQuery")
        try {
            sql.execute(insertQuery, ["acceptedTerms": Utility.convertBoolToYesNo(application.acceptedTerms),
                                   "acceptedTermsTimestamp": application.acceptedTermsTimestamp != null ? Timestamp.valueOf(application.acceptedTermsTimestamp) : null,
                                   "phoneType": application.phoneType,
                                   "ipAddressAtAccountCreation": application.ipAddressAtAccountCreation,
                                   "ipAddressAtAppCreation": application.ipAddressAtAppCreation,
                                   "preferredMethodOfContact": application.preferredMethodOfContact,
                                   "mainphoneVerified": Utility.convertBoolToYesNo(application.mainphoneVerified),
                                   "mainphoneVerifiedTimestamp": application.mainphoneVerifiedTimestamp != null ? Timestamp.valueOf(application.mainphoneVerifiedTimestamp) : null,
                                   "emailVerified": Utility.convertBoolToYesNo(application.emailVerified),
                                   "emailVerifiedTimestamp": application.emailVerifiedTimestamp != null ? Timestamp.valueOf(application.emailVerifiedTimestamp) : null,
                                   "addressValidationOverride": Utility.convertBoolToYesNo(application.addressValidationOverride),
                                   "addressValidationOverrideTimestamp": application.addressValidationOverrideTimestamp != null ? Timestamp.valueOf(application.addressValidationOverrideTimestamp) : null,
                                   "agentEmail": application.agentEmail,
                                   "appId": application.appId,
                                    "cccId": application.cccId, 
                                    "collegeId": application.collegeId,
                                    "addressVerified": Utility.convertBoolToYesNo(application.addressVerified), 
                                    "agentPhoneExt": application.agentPhoneExt, 
                                    "agentPhoneNumber": application.agentPhoneNumber, 
                                    "altNonUsPhoneAuthTxt": Utility.convertBoolToYesNo(application.altNonUsPhoneAuthTxt),
                                    "altNonUsPhoneExt": application.altNonUsPhoneExt, 
                                    "altNonUsPhoneNumber": application.altNonUsPhoneNumber, 
                                    "appLang": application.appLang, 
                                    "authorizeAgentInfoRelease": Utility.convertBoolToYesNo(application.authorizeAgentInfoRelease),
                                    "birthdate": application.birthdate != null ? Date.valueOf(application.birthdate): null,
                                    "campaign1": application.campaign1, 
                                    "campaign2": application.campaign2, 
                                    "campaign3": application.campaign3, 
                                    "citizenshipStatus": application.citizenshipStatus,
                                    "city": application.city, 
                                    "coenrollConfirm": application.coenrollConfirm, 
                                    "col1Cds": application.col1Cds, 
                                    "col1Ceeb": application.col1Ceeb, 
                                    "col1City": application.col1City, 
                                    "col1CollegeAttendedId": application.col1CollegeAttendedId,
                                   "col1Country": application.col1Country,
                                   "col1DegreeDate": application.col1DegreeDate != null ? Date.valueOf(application.col1DegreeDate): null,
                                   "col1DegreeObtained": application.col1DegreeObtained,
                                   "col1EndDate": application.col1EndDate != null ? Date.valueOf(application.col1EndDate): null,
                                   "col1ExpelledStatus": Utility.convertBoolToYesNo(application.col1ExpelledStatus),
                                   "col1Major": application.col1Major,
                                   "col1Name": application.col1Name,
                                   "col1NonUsProvince": application.col1NonUsProvince,
                                   "col1NotListed": Utility.convertBoolToYesNo(application.col1NotListed),
                                   "col1PrimaryInstructionLanguage": application.col1PrimaryInstructionLanguage,
                                   "col1StartDate": application.col1StartDate != null ? Date.valueOf(application.col1StartDate): null,
                                   "col1State": application.col1State,
                                   "col2Cds": application.col2Cds,
                                   "col2Ceeb": application.col2Ceeb,
                                   "col2City": application.col2City,
                                   "col2CollegeAttendedId": application.col2CollegeAttendedId,
                                   "col2Country": application.col2Country,
                                   "col2DegreeDate": application.col2DegreeDate != null ? Date.valueOf(application.col2DegreeDate): null,
                                   "col2DegreeObtained": application.col2DegreeObtained,
                                   "col2EndDate": application.col2EndDate != null ? Date.valueOf(application.col2EndDate): null,
                                   "col2ExpelledStatus": Utility.convertBoolToYesNo(application.col2ExpelledStatus),
                                   "col2Major": application.col2Major,
                                   "col2Name": application.col2Name,
                                   "col2NonUsProvince": application.col2NonUsProvince,
                                   "col2NotListed": Utility.convertBoolToYesNo(application.col2NotListed),
                                   "col2PrimaryInstructionLanguage": application.col2PrimaryInstructionLanguage,
                                   "col2StartDate": application.col2StartDate != null ? Date.valueOf(application.col2StartDate): null,
                                   "col2State": application.col2State,
                                   "col3Cds": application.col3Cds,
                                   "col3Ceeb": application.col3Ceeb,
                                   "col3City": application.col3City,
                                   "col3CollegeAttendedId": application.col3CollegeAttendedId,
                                   "col3Country": application.col3Country,
                                   "col3DegreeDate": application.col3DegreeDate != null ? Date.valueOf(application.col3DegreeDate): null,
                                   "col3DegreeObtained": application.col3DegreeObtained,
                                   "col3EndDate": application.col3EndDate != null ? Date.valueOf(application.col3EndDate): null,
                                   "col3ExpelledStatus": Utility.convertBoolToYesNo(application.col3ExpelledStatus),
                                   "col3Major": application.col3Major,
                                   "col3Name": application.col3Name,
                                   "col3NonUsProvince": application.col3NonUsProvince,
                                   "col3NotListed": Utility.convertBoolToYesNo(application.col3NotListed),
                                   "col3PrimaryInstructionLanguage": application.col3PrimaryInstructionLanguage,
                                   "col3StartDate": application.col3StartDate != null ? Date.valueOf(application.col3StartDate): null,
                                   "col3State": application.col3State,
                                   "col4Cds": application.col4Cds,
                                   "col4Ceeb": application.col4Ceeb,
                                   "col4City": application.col4City,
                                   "col4CollegeAttendedId": application.col4CollegeAttendedId,
                                   "col4Country": application.col4Country,
                                   "col4DegreeDate": application.col4DegreeDate != null ? Date.valueOf(application.col4DegreeDate): null,
                                   "col4DegreeObtained": application.col4DegreeObtained,
                                   "col4EndDate": application.col4EndDate != null ? Date.valueOf(application.col4EndDate): null,
                                   "col4ExpelledStatus": Utility.convertBoolToYesNo(application.col4ExpelledStatus),
                                   "col4Major": application.col4Major,
                                   "col4Name": application.col4Name,
                                   "col4NonUsProvince": application.col4NonUsProvince,
                                   "col4NotListed": Utility.convertBoolToYesNo(application.col4NotListed),
                                   "col4PrimaryInstructionLanguage": application.col4PrimaryInstructionLanguage,
                                   "col4StartDate": application.col4StartDate != null ? Date.valueOf(application.col4StartDate): null,
                                   "col4State": application.col4State,
                                   "collegeCompDate": application.collegeCompDate != null ? Date.valueOf(application.collegeCompDate): null,
                                   "collegeCount": application.collegeCount,
                                   "collegeEduLevel": application.collegeEduLevel,
                                   "collegeExpelledSummary": Utility.convertBoolToYesNo(application.collegeExpelledSummary),
                                   "collegeName": application.collegeName,
                                   "company": application.company,
                                   "confirmation": application.confirmation,
                                   "consent": Utility.convertBoolToYesNo(application.consent),
                                   "contact": application.contact,
                                   "country": application.country,
                                   "countryOfBirth": application.countryOfBirth,
                                   "countryOfCitizenship": application.countryOfCitizenship,
                                   "cryptokeyid": application.cryptokeyid,
                                   "currentMailingAddressOutsideUs": Utility.convertBoolToYesNo(application.currentMailingAddressOutsideUs),
                                   "currentMailingAddressVerified": Utility.convertBoolToYesNo(application.currentMailingAddressVerified),
                                   "currentMailingCity": application.currentMailingCity,
                                   "currentMailingCountry": application.currentMailingCountry,
                                   "currentMailingNonUsAddress": Utility.convertBoolToYesNo(application.currentMailingNonUsAddress),
                                   "currentMailingNonUsPostalCode": application.currentMailingNonUsPostalCode,
                                   "currentMailingNonUsProvince": application.currentMailingNonUsProvince,
                                   "currentMailingSameAsPermanent": Utility.convertBoolToYesNo(application.currentMailingSameAsPermanent),
                                   "currentMailingState": application.currentMailingState,
                                   "currentMailingStreet1": application.currentMailingStreet1,
                                   "currentMailingStreet2": application.currentMailingStreet2,
                                   "currentMailingZipCode": application.currentMailingZipCode,
                                   "dep1CountryOfBirth": application.dep1CountryOfBirth,
                                   "dep1DateOfBirth": application.dep1DateOfBirth != null ? Date.valueOf(application.dep1DateOfBirth): null,
                                   "dep1DependentId": application.dep1DependentId,
                                   "dep1FirstName": application.dep1FirstName,
                                   "dep1Gender": application.dep1Gender,
                                   "dep1LastName": application.dep1LastName,
                                   "dep1NoFirstName": Utility.convertBoolToYesNo(application.dep1NoFirstName),
                                   "dep1Relationship": application.dep1Relationship,
                                   "dep10CountryOfBirth": application.dep10CountryOfBirth,
                                   "dep10DateOfBirth": application.dep10DateOfBirth != null ? Date.valueOf(application.dep10DateOfBirth): null,
                                   "dep10DependentId": application.dep10DependentId,
                                   "dep10FirstName": application.dep10FirstName,
                                   "dep10Gender": application.dep10Gender,
                                   "dep10LastName": application.dep10LastName,
                                   "dep10NoFirstName": Utility.convertBoolToYesNo(application.dep10NoFirstName),
                                   "dep10Relationship": application.dep10Relationship,
                                   "dep2CountryOfBirth": application.dep2CountryOfBirth,
                                   "dep2DateOfBirth": application.dep2DateOfBirth != null ? Date.valueOf(application.dep2DateOfBirth): null,
                                   "dep2DependentId": application.dep2DependentId,
                                   "dep2FirstName": application.dep2FirstName,
                                   "dep2Gender": application.dep2Gender,
                                   "dep2LastName": application.dep2LastName,
                                   "dep2NoFirstName": Utility.convertBoolToYesNo(application.dep2NoFirstName),
                                   "dep2Relationship": application.dep2Relationship,
                                   "dep3CountryOfBirth": application.dep3CountryOfBirth,
                                   "dep3DateOfBirth": application.dep3DateOfBirth != null ? Date.valueOf(application.dep3DateOfBirth): null,
                                   "dep3DependentId": application.dep3DependentId,
                                   "dep3FirstName": application.dep3FirstName,
                                   "dep3Gender": application.dep3Gender,
                                   "dep3LastName": application.dep3LastName,
                                   "dep3NoFirstName": Utility.convertBoolToYesNo(application.dep3NoFirstName),
                                   "dep3Relationship": application.dep3Relationship,
                                   "dep4CountryOfBirth": application.dep4CountryOfBirth,
                                   "dep4DateOfBirth": application.dep4DateOfBirth != null ? Date.valueOf(application.dep4DateOfBirth): null,
                                   "dep4DependentId": application.dep4DependentId,
                                   "dep4FirstName": application.dep4FirstName,
                                   "dep4Gender": application.dep4Gender,
                                   "dep4LastName": application.dep4LastName,
                                   "dep4NoFirstName": Utility.convertBoolToYesNo(application.dep4NoFirstName),
                                   "dep4Relationship": application.dep4Relationship,
                                   "dep5CountryOfBirth": application.dep5CountryOfBirth,
                                   "dep5DateOfBirth": application.dep5DateOfBirth != null ? Date.valueOf(application.dep5DateOfBirth): null,
                                   "dep5DependentId": application.dep5DependentId,
                                   "dep5FirstName": application.dep5FirstName,
                                   "dep5Gender": application.dep5Gender,
                                   "dep5LastName": application.dep5LastName,
                                   "dep5NoFirstName": Utility.convertBoolToYesNo(application.dep5NoFirstName),
                                   "dep5Relationship": application.dep5Relationship,
                                   "dep6CountryOfBirth": application.dep6CountryOfBirth,
                                   "dep6DateOfBirth": application.dep6DateOfBirth != null ? Date.valueOf(application.dep6DateOfBirth): null,
                                   "dep6DependentId": application.dep6DependentId,
                                   "dep6FirstName": application.dep6FirstName,
                                   "dep6Gender": application.dep6Gender,
                                   "dep6LastName": application.dep6LastName,
                                   "dep6NoFirstName": Utility.convertBoolToYesNo(application.dep6NoFirstName),
                                   "dep6Relationship": application.dep6Relationship,
                                   "dep7CountryOfBirth": application.dep7CountryOfBirth,
                                   "dep7DateOfBirth": application.dep7DateOfBirth != null ? Date.valueOf(application.dep7DateOfBirth): null,
                                   "dep7DependentId": application.dep7DependentId,
                                   "dep7FirstName": application.dep7FirstName,
                                   "dep7Gender": application.dep7Gender,
                                   "dep7LastName": application.dep7LastName,
                                   "dep7NoFirstName": Utility.convertBoolToYesNo(application.dep7NoFirstName),
                                   "dep7Relationship": application.dep7Relationship,
                                   "dep8CountryOfBirth": application.dep8CountryOfBirth,
                                   "dep8DateOfBirth": application.dep8DateOfBirth != null ? Date.valueOf(application.dep8DateOfBirth): null,
                                   "dep8DependentId": application.dep8DependentId,
                                   "dep8FirstName": application.dep8FirstName,
                                   "dep8Gender": application.dep8Gender,
                                   "dep8LastName": application.dep8LastName,
                                   "dep8NoFirstName": Utility.convertBoolToYesNo(application.dep8NoFirstName),
                                   "dep8Relationship": application.dep8Relationship,
                                   "dep9CountryOfBirth": application.dep9CountryOfBirth,
                                   "dep9DateOfBirth": application.dep9DateOfBirth != null ? Date.valueOf(application.dep9DateOfBirth): null,
                                   "dep9DependentId": application.dep9DependentId,
                                   "dep9FirstName": application.dep9FirstName,
                                   "dep9Gender": application.dep9Gender,
                                   "dep9LastName": application.dep9LastName,
                                   "dep9NoFirstName": Utility.convertBoolToYesNo(application.dep9NoFirstName),
                                   "dep9Relationship": application.dep9Relationship,
                                   "educationalGoal": application.educationalGoal,
                                   "email": application.email,
                                   "emergencyContactAddressVerified": Utility.convertBoolToYesNo(application.emergencyContactAddressVerified),
                                   "emergencyContactCity": application.emergencyContactCity,
                                   "emergencyContactCountry": application.emergencyContactCountry,
                                   "emergencyContactEmail": application.emergencyContactEmail,
                                   "emergencyContactFirstName": application.emergencyContactFirstName,
                                   "emergencyContactLastName": application.emergencyContactLastName,
                                   "emergencyContactNoFirstName": Utility.convertBoolToYesNo(application.emergencyContactNoFirstName),
                                   "emergencyContactNonUsAddress": Utility.convertBoolToYesNo(application.emergencyContactNonUsAddress),
                                   "emergencyContactNonUsPostalCode": application.emergencyContactNonUsPostalCode,
                                   "emergencyContactNonUsProvince": application.emergencyContactNonUsProvince,
                                   "emergencyContactPhoneAuthTxt": Utility.convertBoolToYesNo(application.emergencyContactPhoneAuthTxt),
                                   "emergencyContactPhoneExt": application.emergencyContactPhoneExt,
                                   "emergencyContactPhoneNumber": application.emergencyContactPhoneNumber,
                                   "emergencyContactRelationship": application.emergencyContactRelationship,
                                   "emergencyContactState": application.emergencyContactState,
                                   "emergencyContactStreet1": application.emergencyContactStreet1,
                                   "emergencyContactStreet2": application.emergencyContactStreet2,
                                   "emergencyContactZipCode": application.emergencyContactZipCode,
                                   "engMonthsStudied": application.engMonthsStudied,
                                   "engProficiencyDate": application.engProficiencyDate != null ? Date.valueOf(application.engProficiencyDate): null,
                                   "engProficiencyOther": application.engProficiencyOther,
                                   "engProficiencyPrerequisite": Utility.convertBoolToYesNo(application.engProficiencyPrerequisite),
                                   "engProficiencyReq": application.engProficiencyReq,
                                   "engProficiencyScore": application.engProficiencyScore,
                                   "engProficiencyShowScore": Utility.convertBoolToYesNo(application.engProficiencyShowScore),
                                   "engProficiencyType": application.engProficiencyType,
                                   "enrollStatus": application.enrollStatus,
                                   "enrollTermCode": application.enrollTermCode,
                                   "enrollTermDescription": application.enrollTermDescription,
                                   "esignature": Utility.convertBoolToYesNo(application.esignature),
                                   "expirationDate": application.expirationDate != null ? Date.valueOf(application.expirationDate): null,
                                   "faxNumberNumber": application.faxNumberNumber,
                                   "firstname": application.firstname,
                                   "gender": application.gender,
                                   "higherLang": application.higherLang,
                                   "highestCompDate": application.highestCompDate != null ? Date.valueOf(application.highestCompDate): null,
                                   "highestEduLevel": application.highestEduLevel,
                                   "hispanic": Utility.convertBoolToYesNo(application.hispanic),
                                   "hsAddressVerified": Utility.convertBoolToYesNo(application.hsAddressVerified),
                                   "hsCds": application.hsCds,
                                   "hsCeeb": application.hsCeeb,
                                   "hsCity": application.hsCity,
                                   "hsCompDate": application.hsCompDate != null ? Date.valueOf(application.hsCompDate): null,
                                   "hsCountry": application.hsCountry,
                                   "hsDiplomaCert": application.hsDiplomaCert,
                                   "hsDiplomaCertDate": application.hsDiplomaCertDate != null ? Date.valueOf(application.hsDiplomaCertDate): null,
                                   "hsEduLevel": application.hsEduLevel,
                                   "hsEndDate": application.hsEndDate != null ? Date.valueOf(application.hsEndDate): null,
                                   "hsLang": application.hsLang,
                                   "hsName": application.hsName,
                                   "hsNonUsAddress": Utility.convertBoolToYesNo(application.hsNonUsAddress),
                                   "hsNonUsPostalCode": application.hsNonUsPostalCode,
                                   "hsNonUsProvince": application.hsNonUsProvince,
                                   "hsNotListed": Utility.convertBoolToYesNo(application.hsNotListed),
                                   "hsStartDate": application.hsStartDate != null ? Date.valueOf(application.hsStartDate): null,
                                   "hsState": application.hsState,
                                   "hsStreet1": application.hsStreet1,
                                   "hsStreet2": application.hsStreet2,
                                   "hsType": application.hsType,
                                   "hsZipCode": application.hsZipCode,
                                   "i20ExpirationDate": application.i20ExpirationDate != null ? Date.valueOf(application.i20ExpirationDate): null,
                                   "i20IssuingSchoolName": application.i20IssuingSchoolName,
                                   "i94AdmissionNumber": application.i94AdmissionNumber,
                                   "i94ExpirationDate": application.i94ExpirationDate != null ? Date.valueOf(application.i94ExpirationDate): null,
                                   "intended4YearMajor": application.intended4YearMajor,
                                   "ipAddress": application.ipAddress,
                                   "issueDate": application.issueDate != null ? Date.valueOf(application.issueDate): null,
                                   "lastPage": application.lastPage,
                                   "lastname": application.lastname,
                                   "mainPhoneAuthTxt": Utility.convertBoolToYesNo(application.mainPhoneAuthTxt),
                                   "mainPhoneExt": application.mainPhoneExt,
                                   "mainPhoneNumber": application.mainPhoneNumber,
                                   "majorCode": application.majorCode,
                                   "majorDescription": application.majorDescription,
                                   "middlename": application.middlename,
                                   "noI94ExpirationDate": Utility.convertBoolToYesNo(application.noI94ExpirationDate),
                                   "noVisa": Utility.convertBoolToYesNo(application.noVisa),
                                   "nonUsAddress": Utility.convertBoolToYesNo(application.nonUsAddress),
                                   "nonUsPermanentHomeAddressSameAsPermanent": Utility.convertBoolToYesNo(application.nonUsPermanentHomeAddressSameAsPermanent),
                                   "nonUsPermanentHomeAddressVerified": Utility.convertBoolToYesNo(application.nonUsPermanentHomeAddressVerified),
                                   "nonUsPermanentHomeCity": application.nonUsPermanentHomeCity,
                                   "nonUsPermanentHomeCountry": application.nonUsPermanentHomeCountry,
                                   "nonUsPermanentHomeNonUsAddress": Utility.convertBoolToYesNo(application.nonUsPermanentHomeNonUsAddress),
                                   "nonUsPermanentHomeNonUsPostalCode": application.nonUsPermanentHomeNonUsPostalCode,
                                   "nonUsPermanentHomeNonUsProvince": application.nonUsPermanentHomeNonUsProvince,
                                   "nonUsPermanentHomeStreet1": application.nonUsPermanentHomeStreet1,
                                   "nonUsPermanentHomeStreet2": application.nonUsPermanentHomeStreet2,
                                   "nonUsPhoneAuthTxt": Utility.convertBoolToYesNo(application.nonUsPhoneAuthTxt),
                                   "nonUsPhoneExt": application.nonUsPhoneExt,
                                   "nonUsPhoneNumber": application.nonUsPhoneNumber,
                                   "nonUsPostalCode": application.nonUsPostalCode,
                                   "nonUsProvince": application.nonUsProvince,
                                   "numberOfDependents": application.numberOfDependents,
                                   "numberOfPracticalTraining": application.numberOfPracticalTraining,
                                   "otherfirstname": application.otherfirstname,
                                   "otherlastname": application.otherlastname,
                                   "othermiddlename": application.othermiddlename,
                                   "parentGuardianAddressVerified": Utility.convertBoolToYesNo(application.parentGuardianAddressVerified),
                                   "parentGuardianCity": application.parentGuardianCity,
                                   "parentGuardianCountry": application.parentGuardianCountry,
                                   "parentGuardianEmail": application.parentGuardianEmail,
                                   "parentGuardianFirstName": application.parentGuardianFirstName,
                                   "parentGuardianLastName": application.parentGuardianLastName,
                                   "parentGuardianNoFirstName": Utility.convertBoolToYesNo(application.parentGuardianNoFirstName),
                                   "parentGuardianNonUsAddress": Utility.convertBoolToYesNo(application.parentGuardianNonUsAddress),
                                   "parentGuardianNonUsPostalCode": application.parentGuardianNonUsPostalCode,
                                   "parentGuardianNonUsProvince": application.parentGuardianNonUsProvince,
                                   "parentGuardianPhoneAuthTxt": Utility.convertBoolToYesNo(application.parentGuardianPhoneAuthTxt),
                                   "parentGuardianPhoneExt": application.parentGuardianPhoneExt,
                                   "parentGuardianPhoneNumber": application.parentGuardianPhoneNumber,
                                   "parentGuardianRelationship": application.parentGuardianRelationship,
                                   "parentGuardianState": application.parentGuardianState,
                                   "parentGuardianStreet1": application.parentGuardianStreet1,
                                   "parentGuardianStreet2": application.parentGuardianStreet2,
                                   "parentGuardianZipCode": application.parentGuardianZipCode,
                                   "passportCountryOfIssuance": application.passportCountryOfIssuance,
                                   "passportExpirationDate": application.passportExpirationDate != null ? Date.valueOf(application.passportExpirationDate): null,
                                   "passportNotYet": Utility.convertBoolToYesNo(application.passportNotYet),
                                   "passportNumber": application.passportNumber,
                                   "permAddrAddressVerified": Utility.convertBoolToYesNo(application.permAddrAddressVerified),
                                   "permAddrCity": application.permAddrCity,
                                   "permAddrCountry": application.permAddrCountry,
                                   "permAddrNonUsAddress": Utility.convertBoolToYesNo(application.permAddrNonUsAddress),
                                   "permAddrNonUsPostalCode": application.permAddrNonUsPostalCode,
                                   "permAddrNonUsProvince": application.permAddrNonUsProvince,
                                   "permAddrState": application.permAddrState,
                                   "permAddrStreet1": application.permAddrStreet1,
                                   "permAddrStreet2": application.permAddrStreet2,
                                   "permAddrZipCode": application.permAddrZipCode,
                                   "phoneAuthTxt": Utility.convertBoolToYesNo(application.phoneAuthTxt),
                                   "phoneExt": application.phoneExt,
                                   "phoneNumber": application.phoneNumber,
                                   "preferredFirstname": application.preferredFirstname,
                                   "preferredLastname": application.preferredLastname,
                                   "preferredMiddlename": application.preferredMiddlename,
                                   "preferredName": Utility.convertBoolToYesNo(application.preferredName),
                                   "presentlyStudyingInUs": Utility.convertBoolToYesNo(application.presentlyStudyingInUs),
                                   "primaryLanguage": application.primaryLanguage,
                                   "pt1AuthorizingSchool": application.pt1AuthorizingSchool,
                                   "pt1EndDate": application.pt1EndDate != null ? Date.valueOf(application.pt1EndDate): null,
                                   "pt1PracticalTrainingId": application.pt1PracticalTrainingId,
                                   "pt1StartDate": application.pt1StartDate != null ? Date.valueOf(application.pt1StartDate): null,
                                   "pt1Type": application.pt1Type,
                                   "pt2AuthorizingSchool": application.pt2AuthorizingSchool,
                                   "pt2EndDate": application.pt2EndDate != null ? Date.valueOf(application.pt2EndDate): null,
                                   "pt2PracticalTrainingId": application.pt2PracticalTrainingId,
                                   "pt2StartDate": application.pt2StartDate != null ? Date.valueOf(application.pt2StartDate): null,
                                   "pt2Type": application.pt2Type,
                                   "pt3AuthorizingSchool": application.pt3AuthorizingSchool,
                                   "pt3EndDate": application.pt3EndDate != null ? Date.valueOf(application.pt3EndDate): null,
                                   "pt3PracticalTrainingId": application.pt3PracticalTrainingId,
                                   "pt3StartDate": application.pt3StartDate != null ? Date.valueOf(application.pt3StartDate): null,
                                   "pt3Type": application.pt3Type,
                                   "pt4AuthorizingSchool": application.pt4AuthorizingSchool,
                                   "pt4EndDate": application.pt4EndDate != null ? Date.valueOf(application.pt4EndDate): null,
                                   "pt4PracticalTrainingId": application.pt4PracticalTrainingId,
                                   "pt4StartDate": application.pt4StartDate != null ? Date.valueOf(application.pt4StartDate): null,
                                   "pt4Type": application.pt4Type,
                                   "raceEthnicity": application.raceEthnicity,
                                   "raceEthnicFull": application.raceEthnicFull,
                                   "raceGroup": application.raceGroup,
                                   "salt": application.salt,
                                   "secondPhoneAuthTxt": Utility.convertBoolToYesNo(application.secondPhoneAuthTxt),
                                   "secondPhoneExt": application.secondPhoneExt,
                                   "secondPhoneNumber": application.secondPhoneNumber,
                                   "sevisIdNumber": application.sevisIdNumber,
                                   "signature": application.signature,
                                   "ssn": application.ssn,
                                   "ssnException": Utility.convertBoolToYesNo(application.ssnException),
                                   "ssnLast4": application.ssnLast4,
                                   "ssnType": application.ssnType,
                                   "state": application.state,
                                   "status": application.status,
                                   "street1": application.street1,
                                   "street2": application.street2,
                                   "suffix": application.suffix,
                                   "supPageCode": application.supPageCode,
                                   "termEndDate": application.termEndDate != null ? Date.valueOf(application.termEndDate): null,
                                   "termStartDate": application.termStartDate != null ? Date.valueOf(application.termStartDate): null,
                                   "tstmpCreate": application.tstmpCreate != null ? Timestamp.valueOf(application.tstmpCreate): null,
                                   "tstmpDownload": application.tstmpDownload != null ? Timestamp.valueOf(application.tstmpDownload): null,
                                   "tstmpSubmit": application.tstmpSubmit != null ? Timestamp.valueOf(application.tstmpSubmit): null,
                                   "tstmpUpdate": application.tstmpUpdate != null ? Timestamp.valueOf(application.tstmpUpdate): null,
                                   "visaType": application.visaType,
                                   "zipCode": application.zipCode,
                                   "cipCode": application.cipCode,
                                   "col1CdsFull": application.col1CdsFull,
                                   "col2CdsFull": application.col2CdsFull,
                                   "col3CdsFull": application.col3CdsFull,
                                   "col4CdsFull": application.col4CdsFull,
                                   "hsCdsFull": application.hsCdsFull,
                                   "majorCategory": application.majorCategory,
                                   "noMailingAddressHomeless": Utility.convertBoolToYesNo(application.noMailingAddressHomeless),
                                   "noNonUsaPermAddressHomeless": Utility.convertBoolToYesNo(application.noNonUsaPermAddressHomeless),
                                   "noPermAddressHomeless": Utility.convertBoolToYesNo(application.noPermAddressHomeless),
                                   "ssnNo": Utility.convertBoolToYesNo(application.ssnNo),
                                   "suppText01": application.supplementalQuestions?.suppText01,
                                   "suppText02": application.supplementalQuestions?.suppText02,
                                   "suppText03": application.supplementalQuestions?.suppText03,
                                   "suppText04": application.supplementalQuestions?.suppText04,
                                   "suppText05": application.supplementalQuestions?.suppText05,
                                   "suppText06": application.supplementalQuestions?.suppText06,
                                   "suppText07": application.supplementalQuestions?.suppText07,
                                   "suppText08": application.supplementalQuestions?.suppText08,
                                   "suppText09": application.supplementalQuestions?.suppText09,
                                   "suppText10": application.supplementalQuestions?.suppText10,
                                   "suppText11": application.supplementalQuestions?.suppText11,
                                   "suppText12": application.supplementalQuestions?.suppText12,
                                   "suppText13": application.supplementalQuestions?.suppText13,
                                   "suppText14": application.supplementalQuestions?.suppText14,
                                   "suppText15": application.supplementalQuestions?.suppText15,
                                   "suppText16": application.supplementalQuestions?.suppText16,
                                   "suppText17": application.supplementalQuestions?.suppText17,
                                   "suppText18": application.supplementalQuestions?.suppText18,
                                   "suppText19": application.supplementalQuestions?.suppText19,
                                   "suppText20": application.supplementalQuestions?.suppText20,
                                   "suppCheck01": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck01),
                                   "suppCheck02": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck02),
                                   "suppCheck03": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck03),
                                   "suppCheck04": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck04),
                                   "suppCheck05": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck05),
                                   "suppCheck06": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck06),
                                   "suppCheck07": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck07),
                                   "suppCheck08": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck08),
                                   "suppCheck09": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck09),
                                   "suppCheck10": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck10),
                                   "suppCheck11": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck11),
                                   "suppCheck12": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck12),
                                   "suppCheck13": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck13),
                                   "suppCheck14": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck14),
                                   "suppCheck15": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck15),
                                   "suppCheck16": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck16),
                                   "suppCheck17": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck17),
                                   "suppCheck18": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck18),
                                   "suppCheck19": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck19),
                                   "suppCheck20": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck20),
                                   "suppCheck21": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck21),
                                   "suppCheck22": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck22),
                                   "suppCheck23": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck23),
                                   "suppCheck24": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck24),
                                   "suppCheck25": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck25),
                                   "suppCheck26": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck26),
                                   "suppCheck27": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck27),
                                   "suppCheck28": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck28),
                                   "suppCheck29": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck29),
                                   "suppCheck30": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck30),
                                   "suppCheck31": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck31),
                                   "suppCheck32": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck32),
                                   "suppCheck33": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck33),
                                   "suppCheck34": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck34),
                                   "suppCheck35": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck35),
                                   "suppCheck36": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck36),
                                   "suppCheck37": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck37),
                                   "suppCheck38": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck38),
                                   "suppCheck39": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck39),
                                   "suppCheck40": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck40),
                                   "suppCheck41": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck41),
                                   "suppCheck42": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck42),
                                   "suppCheck43": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck43),
                                   "suppCheck44": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck44),
                                   "suppCheck45": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck45),
                                   "suppCheck46": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck46),
                                   "suppCheck47": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck47),
                                   "suppCheck48": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck48),
                                   "suppCheck49": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck49),
                                   "suppCheck50": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppCheck50),
                                   "suppYesno01": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno01),
                                   "suppYesno02": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno02),
                                   "suppYesno03": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno03),
                                   "suppYesno04": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno04),
                                   "suppYesno05": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno05),
                                   "suppYesno06": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno06),
                                   "suppYesno07": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno07),
                                   "suppYesno08": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno08),
                                   "suppYesno09": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno09),
                                   "suppYesno10": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno10),
                                   "suppYesno11": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno11),
                                   "suppYesno12": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno12),
                                   "suppYesno13": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno13),
                                   "suppYesno14": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno14),
                                   "suppYesno15": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno15),
                                   "suppYesno16": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno16),
                                   "suppYesno17": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno17),
                                   "suppYesno18": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno18),
                                   "suppYesno19": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno19),
                                   "suppYesno20": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno20),
                                   "suppYesno21": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno21),
                                   "suppYesno22": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno22),
                                   "suppYesno23": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno23),
                                   "suppYesno24": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno24),
                                   "suppYesno25": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno25),
                                   "suppYesno26": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno26),
                                   "suppYesno27": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno27),
                                   "suppYesno28": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno28),
                                   "suppYesno29": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno29),
                                   "suppYesno30": Utility.convertBoolToYesNo(application.supplementalQuestions?.suppYesno30),
                                   "suppMenu01": application.supplementalQuestions?.suppMenu01,
                                   "suppMenu02": application.supplementalQuestions?.suppMenu02,
                                   "suppMenu03": application.supplementalQuestions?.suppMenu03,
                                   "suppMenu04": application.supplementalQuestions?.suppMenu04,
                                   "suppMenu05": application.supplementalQuestions?.suppMenu05,
                                   "suppMenu06": application.supplementalQuestions?.suppMenu06,
                                   "suppMenu07": application.supplementalQuestions?.suppMenu07,
                                   "suppMenu08": application.supplementalQuestions?.suppMenu08,
                                   "suppMenu09": application.supplementalQuestions?.suppMenu09,
                                   "suppMenu10": application.supplementalQuestions?.suppMenu10,
                                   "suppMenu11": application.supplementalQuestions?.suppMenu11,
                                   "suppMenu12": application.supplementalQuestions?.suppMenu12,
                                   "suppMenu13": application.supplementalQuestions?.suppMenu13,
                                   "suppMenu14": application.supplementalQuestions?.suppMenu14,
                                   "suppMenu15": application.supplementalQuestions?.suppMenu15,
                                   "suppMenu16": application.supplementalQuestions?.suppMenu16,
                                   "suppMenu17": application.supplementalQuestions?.suppMenu17,
                                   "suppMenu18": application.supplementalQuestions?.suppMenu18,
                                   "suppMenu19": application.supplementalQuestions?.suppMenu19,
                                   "suppMenu20": application.supplementalQuestions?.suppMenu20,
                                   "suppMenu21": application.supplementalQuestions?.suppMenu21,
                                   "suppMenu22": application.supplementalQuestions?.suppMenu22,
                                   "suppMenu23": application.supplementalQuestions?.suppMenu23,
                                   "suppMenu24": application.supplementalQuestions?.suppMenu24,
                                   "suppMenu25": application.supplementalQuestions?.suppMenu25,
                                   "suppMenu26": application.supplementalQuestions?.suppMenu26,
                                   "suppMenu27": application.supplementalQuestions?.suppMenu27,
                                   "suppMenu28": application.supplementalQuestions?.suppMenu28,
                                   "suppMenu29": application.supplementalQuestions?.suppMenu29,
                                   "suppMenu30": application.supplementalQuestions?.suppMenu30,
                                   "suppDate01": application.supplementalQuestions?.suppDate01 != null ? Date.valueOf(application.supplementalQuestions?.suppDate01): null,
                                   "suppDate02": application.supplementalQuestions?.suppDate02 != null ? Date.valueOf(application.supplementalQuestions?.suppDate02): null,
                                   "suppDate03": application.supplementalQuestions?.suppDate03 != null ? Date.valueOf(application.supplementalQuestions?.suppDate03): null,
                                   "suppDate04": application.supplementalQuestions?.suppDate04 != null ? Date.valueOf(application.supplementalQuestions?.suppDate04): null,
                                   "suppDate05": application.supplementalQuestions?.suppDate05 != null ? Date.valueOf(application.supplementalQuestions?.suppDate05): null,
                                   "suppState01": application.supplementalQuestions?.suppState01,
                                   "suppState02": application.supplementalQuestions?.suppState02,
                                   "suppState03": application.supplementalQuestions?.suppState03,
                                   "suppState04": application.supplementalQuestions?.suppState04,
                                   "suppState05": application.supplementalQuestions?.suppState05,
                                   "suppCountry01": application.supplementalQuestions?.suppCountry01,
                                   "suppCountry02": application.supplementalQuestions?.suppCountry02,
                                   "suppCountry03": application.supplementalQuestions?.suppCountry03,
                                   "suppCountry04": application.supplementalQuestions?.suppCountry04,
                                   "suppCountry05": application.supplementalQuestions?.suppCountry05,
                                   "suppPhonenumber01": application.supplementalQuestions?.suppPhonenumber01,
                                   "suppPhonenumber02": application.supplementalQuestions?.suppPhonenumber02,
                                   "suppPhonenumber03": application.supplementalQuestions?.suppPhonenumber03,
                                   "suppPhonenumber04": application.supplementalQuestions?.suppPhonenumber04,
                                   "suppPhonenumber05": application.supplementalQuestions?.suppPhonenumber05,
                                   "suppSecret01": application.supplementalQuestions?.suppSecret01,
                                   "suppSecret02": application.supplementalQuestions?.suppSecret02,
                                   "suppSecret03": application.supplementalQuestions?.suppSecret03,
                                   "suppSecret04": application.supplementalQuestions?.suppSecret04,
                                   "suppSecret05": application.supplementalQuestions?.suppSecret05,
                                   "residesInUs": Utility.convertBoolToYesNo(application.residesInUs),
                                   "idmeConfirmationTimestamp": application.idmeConfirmationTimestamp != null ? Timestamp.valueOf(application.idmeConfirmationTimestamp): null,
                                   "idmeOptinTimestamp": application.idmeOptinTimestamp != null ? Timestamp.valueOf(application.idmeOptinTimestamp): null,
                                   "idmeWorkflowStatus": application.idmeWorkflowStatus])

        }

        catch (Exception e) {
            throw new InternalServerException("Server encountered an error: " + e.getMessage())
        }
    }

    static void mapValues(Map<String, MetaProperty> propertyMap, GroovyRowResult source, Object destination) {
        // map values from SQL Map to any Object
        if(source?.containsKey("emergContactAddressVerified"))
            source.put("emergencyContactAddressVerified", source.get("emergContactAddressVerified"))
        if(source?.containsKey("emergContactNonUsPostalCode"))
            source.put("emergencyContactNonUsPostalCode", source.get("emergContactNonUsPostalCode"))
        if(source?.containsKey("nonUsPrmntHomeAddrSameAsPrmnt"))
            source.put("nonUsPermanentHomeAddressSameAsPermanent", source.get("nonUsPrmntHomeAddrSameAsPrmnt"))
        if(source?.containsKey("nonUsPrmntHomeAddrVerified"))
            source.put("nonUsPermanentHomeAddressVerified", source.get("nonUsPrmntHomeAddrVerified"))
        if(source?.containsKey("nonUsPrmntHomePostalCode"))
            source.put("nonUsPermanentHomeNonUsPostalCode", source.get("nonUsPrmntHomePostalCode"))
        if(source?.containsKey("nonUsPrmntHomeProvince"))
            source.put("nonUsPermanentHomeNonUsProvince", source.get("nonUsPrmntHomeProvince"))
        Utility.mapValues(propertyMap, source, destination)
    }
}